AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: phial-project

Globals:
  Function:
    Timeout: 5

Resources:
  Runtime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - provided
      ContentUri: .
    Metadata:
      BuildMethod: makefile
  App:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Datashaman\Phial\Http\Adapter
      Layers:
        - !Ref Runtime
      Runtime: provided
      ReservedConcurrentExecutions: 10
      # Tracing: Active
      Environment:
        Variables:
          APP_DEBUG: true
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PhialProjectCache
    Metadata:
      BuildMethod: makefile
  PhialProjectCache:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: PhialProjectCache

Outputs:
  AppApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
