AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: phial-project

Resources:
  Runtime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - provided
      ContentUri: .
    Metadata:
      BuildMethod: makefile
  HelloHandler:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Handler: App\HelloHandler
      Layers:
        - !Ref Runtime
      Runtime: provided
      Tracing: Active
    Metadata:
      BuildMethod: makefile
  QueueHandler:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        HelloEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt QueueHandler.Arn
      Handler: App\QueueHandler
      Layers:
        - !Ref Runtime
      Runtime: provided
      Tracing: Active
    Metadata:
      BuildMethod: makefile
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: phial-project
  Queue:
    Type: AWS::SQS::Queue
  QueuePolicy:
    Type: AWS::Lambda::QueuePolicy
    Properties:
      Queues:
        - !Ref Queue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: "sqs:*"
          Resource: "*"
          Condition:
            ArnEquals:
              "aws:SourceArn": !Ref Topic

Outputs:
  HelloHandlerApi:
    Description: "HelloHandler URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
