AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: phial-project

Resources:
  Runtime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - provided
      ContentUri: .
    Metadata:
      BuildMethod: makefile
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Handler: App\Handler
      Layers:
        - !Ref Runtime
      Runtime: provided
    Metadata:
      BuildMethod: makefile

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World Function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
