AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: phial-project

Parameters:
  rdsSecurityGroupIds:
    Type: CommaDelimitedList
    Description: Existing VPC security groups ID's that your Amazon RDS Aurora databse has access to. Separated by commas.
  rdsSubnetIds:
    Type: CommaDelimitedList
    Description: An array of SubnetIds that your Amazon Aurora database has access to. Separated by commas.
  rdsHost:
    Type: String
    Description: The Endpoint of your RDS Proxy
  rdsUser:
    Type: String
    Description: The connection Username for your DB or Cluster
  rdsPassword:
    Type: String
    Description: The connection Password for your DB or Cluster
  rdsDatabase:
    Type: String
    Description: The Name of your Database instance
    Default: mysql
  rdsPort:
    Type: String
    Description: Connection port number for your RDS Proxy
    Default: 3306
  rdsRegion:
    Type: String
    Description: The AWS Region for your DB Proxy

Globals:
  Function:
    Timeout: 5

Resources:
  Runtime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - provided
      ContentUri: .
    Metadata:
      BuildMethod: makefile
  App:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Datashaman\Phial\RequestHandlerAdapter
      Layers:
        - !Ref Runtime
      Runtime: provided
      ReservedConcurrentExecutions: 10
      VpcConfig:
        SecurityGroupIds: !Ref rdsSecurityGroupIds
        SubnetIds: !Ref rdsSubnetIds
      Environment:
        Variables:
          RDS_DATABASE: !Ref rdsDatabase
          RDS_HOST: !Ref rdsHost
          RDS_PASSWORD: !Ref rdsPassword
          RDS_PORT: !Ref rdsPort
          RDS_REGION: !Ref rdsRegion
          RDS_USER: !Ref rdsUser
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: makefile

Outputs:
  AppApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
