AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: phial-project

Resources:
  Runtime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - provided
      ContentUri: .
    Metadata:
      BuildMethod: makefile
  App:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Datashaman\Phial\RequestHandlerAdapter
      Layers:
        - !Ref Runtime
      Runtime: provided
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: makefile

Outputs:
  AppApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
